import React, { useEffect, useState } from "react";
import { navigate, Link } from "@reach/router";

function DeleteTask(props) {
  // The state of 'category' is declared as the category that is passed
  // through the function as a prop.
  const [task, setTask] = useState('');
  const url = "/api/tasks/"+props.taskId;
  useEffect(() => {
    const requestTask = async () => {
      const response = await fetch(url);
      const { data } = await response.json();
      const att = await data.attributes;
      const tas = await att.task;
      setTask(tas);
    };
    requestTask();
  }, []);
  // handleDelete function will delete the given category. If
  // successful, will be redirected to the index page
  const handleDelete = values => {
    const deleteTask = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;
      const response = await fetch(url, {
        method: "DELETE",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        },

      });
      if (response.status === 204) {
        navigate("/"+props.categoriesId);
      }
    };
    deleteTask();
  };


  return (
    <div>
      <h2>Delete task: {task}?</h2>
      <button onClick={handleDelete}>Confirm</button><br/><br/>
      <Link to={'/'+props.categoriesId}>Back</Link>
    </div>
  );
}

export default DeleteTask;
